# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_builddeb.pod

=head1 NOMBRE

dh_builddeb - construye paquetes debian

=head1 SINOPSIS

B<dh_builddeb> [S<I<debhelper opciones>>] [B<--destdir=>I<directorio>] [B<--filename=>I<nombre>] [S<B<--> I<parámetros>>]

=head1 DESCRIPCIÓN

dh_builddeb simplemente llama a L<dpkg-deb(8)> para construir el paquete o
paquetes Debian.

=head1 OPCIONES

=over 4

=item B<--destdir=>I<directorio>

Use esta opción si quiere que los ficheros .deb generados se dejen en un
directorio distinto de ".."

=item B<--filename=>I<nombre>

Use esta opción si quiere forzar un nombre para el fichero .deb generado. ¡No
funciona bien si se genera más de un .deb!

=item B<-u>I<parámetros>

=item B<--> I<parámetros>

Pasa I<parámetros> a L<dpkg-deb(1)> cuando se construye el paquete.

=back

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>

=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>