# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 4.2.21 de debhelper

=head1 NOMBRE

dh_desktop - Registra ficheros .desktop

=head1 SINOPSIS

B<dh_desktop> [S<I<opciones debhelper>>] [B<-p<paquete>>]

=head1 DESCRIPCIÓN

dh_desktop es un programa de debhelper que registra ficheros .desktop.  En la
actualidad no gestiona la instalación de los ficheros, aunque puede que lo haga
en un futuro. Se preocupa de añadir los fragmentos necesario para llamar a
F<update-desktop-database> en los scripts del desarrollador.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Ross Burton <ross@burtonini.com>

=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>

