# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_gencontrol.pod

=head1 NOMBRE

dh_gencontrol - genera e instala el fichero de control

=head1 SINOPSIS

B<dh_gencontrol> [S<I<opciones debhelper>>] [S<B<--> I<parámetros>>]

=head1 DESCRIPCIÓN

dh_gencontrol es un programa de debhelper que genera los ficheros de control, y
los instala en el directorio DEBIAN con los permisos correctos.

El programa es simplemente un envoltorio alrededor de L<dpkg-gencontrol(1)>, al
que llama una vez por cada programa sobre el que actúa, y le pasa algunas
opciones adicionales útiles, incluyendo "-isp".

=head1 OPCIONES

=over 4

=item B<-u>I<parámetros>, B<--dpkg-gencontrol-params>I<parámetros>

=item B<--> I<params>

Pasa "parámetros" a L<dpkg-gencontrol(1)>.

=back

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>

=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>