# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.2 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_gconf.pod

=head1 NOMBRE

dh_gconf - genera scripts para registrar esquemas de GConf

=cut

=head1 SINOPSIS

B<dh_gconf> [S<I<opciones debhelper>>] [B<-p<paquete>>]

=head1 DESCRIPCIÓN

dh_gconf es un programa de debhelper que registra esquemas de GConf.

Genera automáticamente los fragmentos en los scripts de postinst y prerm
necesarios para registrar y des-registrar los esquemas en
etc/gconf/schemas. Estos fragmentos usarán gconftool-2, así que el paquete
deberá depender de gconf2. Este programa añadirá una dependencia a
${misc:Depends}.

El script de postinst además enviará una señal a gconfd-2 de forma que los
esquemas instalados estén disponibles inmediatamente.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Ross Burton <ross@burtonini.com>

=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>


=cut