# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installcron.pod

=head1 NOMBRE

dh_installcron - instala scripts para cron en etc/cron.*

=head1 SINOPSIS

B<dh_installcron> [S<B<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_installcron es un programa de debhelper responsable de instalar scripts para
cron en etc/cron.*/ en los directorios de construcción del paquete. Se instalan
los ficheros debian/paquete.cron.daily, debian/paquete.cron.weekly,
debian/paquete.cron.monthly, y debian/paquete.cron.d.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>