# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.2 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installxfonts.pod

=head1 NOMBRE

dh_installxfonts - registra tipos de letra para X

=head1 SINOPSIS

B<dh_installxfonts> [S<I<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_installxfonts es un programa de debhelper responsable de registrar tipos de
letra para X, de forma que los correspondientes fonts.dir, fonts.alias,
y fonts.scale sean reconstruidos adecuadamente durante la instalación.

Antes de llamar a este programa, debe tener instalados los tipos de letra para X
proporcionados por el paquete en el lugar apropiado del directorio de
construcción, y si tiene un fichero fonts.alias o fonts.scale, debe instalarlos
en el lugar correcto bajo etc/X11/fonts en el directorio de construcción del
paquete.

Su paquete debe depender de xutils (>= 4.0.3) para que las órdenes
update-fonts-* estén disponibles. (Este programa añade la dependencia a
${misc:Depends}.)

Este programa genera automáticamente las órdenes de postinst y postrm necesarias
para registrar los tipos de letra para X. Lea L<dh_installdeb(1)> para una
explicación acerca de como funciona esto.

=head1 NOTAS

Lea L<update-fonts-alias(8)>, L<update-fonts-scale(8)>, y
L<update-fonts-dir(8)> para más información acerca de la instalación de tipos de
letra para X.

Consulte las Normas de Debian, sección 12.8.5. para detalles acerca de manejar
los tipos de letra al estilo de Debian.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>