# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installlogrotate.pod

=head1 NOMBRE

dh_installlogrotate - instala ficheros de configuración de logrotate

=head1 SINOPSIS

B<dh_installlogrotate> [S<I<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_installlogrotate es un programa de debhelper responsable de instalar ficheros
de configuración de logrotate en etc/logrotate.d en los directorios de
construcción del paquete. Se instalan los ficheros llamados
debian/paquete.logrotate.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>