# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installinit.pod

=head1 NOMBRE

dh_installinit - instala scripts de init en los directorios de construcción

=head1 SINOPSIS

B<dh_installinit> [S<I<opciones debhelper>>] [B<--init-script=>I<nombrescript>] [B<-n>] [B<-r>] [B<-d>] [S<B<--> I<parámetros>>]

=head1 DESCRIPCIÓN

dh_installinit es un programa de debhelper responsable de instalar scripts de
init y asociar los ficheros predeterminados en los directorios de construcción
del paquete.

Además genera automáticamente las órdenes de postrm y prerm necesarias para
crear los enlaces simbólicos en /etc/rc*.d/ y arrancar y parar los scripts de
init.

Si existe un fichero debian/paquete.init, se instala en etc/init.d/paquete en el
directorio de construcción del paquete, con "paquete" reemplazado por el nombre
del paquete.

Si existe un fichero llamado debian/paquete.default, se instala en
etc/default/paquete en el directorio de construcción del paquete, con "paquete"
reemplazado por el nombre del paquete.

=head1 OPCIONES

=over 4

=item B<-n>, B<--noscripts>

No modifica los scripts de postinst/postrm/prerm.

=item B<-r>, B<--no-restart-on-upgrade>

No reinicia el script de init después de una actualización.

=item B<--no-start>

No inicia el script de init en una instalación o actualización, o no lo para
cuando se desinstale. Sólo llama a update-rc.d. Útil para scripts de rcS.

=item B<-d>, B<--remove-d>

Elimina la "d" final del nombre del paquete, y usa el resultado del nombre para
el script de init instalado en etc/init.d/ , y el fichero predeterminado se
instala en etc/default/ . Esto puede ser útil para demonios con nombres
finalizados en "d". (Nota: Este parámetro tiene preferencia sobre --init-script).

=item B<-u>I<parámetros> B<--update-rcd-params=>I<parámetros>

=item B<--> I<parámetros>

Pasa "parámetros" a L<update-rc.d(8)>. Si no se especifica se pasa "defaults" a
L<update-rc.d(8)>.

=item B<--init-script=>I<nombrescript>

Usa "nombrescript" como nombre del script de init a instalar en etc/init.d/ (y
también usa este nombre para el fichero defaults, si se instala). Esto es útil
si necesita tener un script de nombre diferente al del paquete. Dese cuenta que
si usa este parámetro, dh_installinit mirará si existe un fichero cuyo nombre se
parezca a "paquete.nombrescript" en el directorio debian/ y si es así lo
instalará preferentemente como el script de init en lugar de los ficheros que
instala normalmente. Esta característica sólo es útil si necesita que el mismo
paquete instale más de un script.

=back

=head1 NOTES

Esta orden no es idempotente. Debe llamarse a "dh_clean -k" entre invocaciones
de esta orden. De otro modo, puede causar que los scripts de mantenimiento
contengan partes duplicadas.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>