# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.2 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installpam.pod

=head1 NOMBRE

dh_installpam - instala ficheros de soporte para pam

=head1 SINOPSIS

B<dh_installpam> [S<I<opciones debhelper>>] [B<-n>] [B<--name=>I<nombre>]

=head1 DESCRIPCIÓN

dh_installpam es un programa de debhelper responsable de instalar ficheros
usados por PAM en los directorios de construcción del paquete.

Si existe un fichero llamado debian/package.pam, se instala en
etc/pam.d/paquete en el directorio de construcción del paquete.

=head1 OPCIONES

=over 4

=item B<--name=>I<nombre>

Busca ficheros con el nombre debian/paquete.nombre.pam y los instala como
etc/pam.d/nombre, en vez de usar los ficheros usuales e instalarlos con el
nombre del paquete.

=back

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>