# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_installlogcheck.pod

=head1 NOMBRE

dh_installlogcheck - instala ficheros de normas para logcheck en etc/logcheck/

=head1 SINOPSIS

B<dh_installlogcheck> [S<B<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_installlocgheck es un programa de debhelper responsable de instalar fichero
de normas para logcheck en subdirectorios de etc/logcheck/ en los directorios de
construcción del paquete. Los fichero debian/quete.logcheck.cracking,
debian/paquete.logcheck.violations, debian/paquete.logcheck.violations.ignore,
debian/paquete.logcheck.ignore.workstation,
debian/paquete.logcheck.ignore.server y
debian/paquete.logcheck.ignore.paranoid se instalan si están presentes.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.
    
=head1 AUTOR

Jon Middleton <jjm@debian.org>


=head1 TRADUCTOR

Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>