# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rudy Godoy <rudy@kernel-panik.org>
# y revisada por Rubén Porras <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_listpackages.pod

=head1 NOMBRE

dh_listpackages - lista paquetes binarios sobre los que actuará debhelper

=head1 SINOPSIS

B<dh_listpackages> [S<I<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_listpackages es un programa de debhelper que retorna una lista de todos los
paquetes binarios sobre los que actuarán las órdenes de debhelper. Si usted
especifica algunas opciones, éste cambiará la lista para coincidir con los
paquetes sobre los que otras órdenes de debhelper podrían actuar si se
especifican las mismas opciones.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>


=head1 TRADUCTOR

Traducción de Rudy Godoy <debian-l10n-spanish@lists.debian.org>