# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rudy Godoy <rudy@kernel-panik.org>
# y revisada por Rubén Porras <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_testdir.pod

=head1 NOMBRE

dh_testdir - comprueba el directorio antes de construir el paquete debian

=head1 SINOPSIS

B<dh_testdir> [S<I<opciones debhelper>>] [S<I<fichero ...>>]

=head1 DESCRIPCIÓN

dh_testdir trata de asegurarse de que usted se encuentre en el directorio
adecuando cuando construya un paquete debian. Éste se asegura de que el fichero
debian/control exista, así como cualquier otro fichero que usted especifique.
En caso contrario finaliza con un error.

=head1 OPCIONES

=over 4

=item I<fichero ...>

Comprueba también la existencia de estos ficheros.

=back

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>

