# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rudy Godoy <rudy@kernel-panik.org>
# y revisada por Rubén Porras <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_testroot.pod

=head1 NOMBRE

dh_testroot - asegura que el paquete sea construido como superusuario

=head1 SINOPSIS

B<dh_testroot> [S<I<opciones debhelper>>]

=head1 DESCRIPCIÓN

dh_testroot simplemente verifica si usted es superusuario. Si no, finaliza
con un error. Los paquetes Debian deben ser construidos como superusuario,
aunque usted puede usar L<fakeroot(1)>

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>

