# (c) 2003 Software in the Public Interest
# Esta traducción ha sido realizada por Rudy Godoy <rudy@kernel-panik.org>
# y revisada por Rubén Porras <nahoo@inicia.es>
# Está basada en la página de manual original:
# versión 1.1 del CVS de
# /cvs/debian-doc/manpages/english/debhelper/dh_undocumented.pod

=head1 NOMBRE

dh_undocumented - programa obsoleto de enlace simbólico a undocumented.7

=head1 SINOPSIS

¡No lo ejecute!

=head1 DESCRIPCIÓN

Este programa se usa para crear enlaces simbólicos a la página de manual
undocumented.7 para páginas de manual no presentes en un paquete. Las
normas de Debian ahora desaprueban el uso de la página de manual 
undocumented.7, y debido a eso este programa no hace nada y no debe
ser usado.

=head1 VÉASE TAMBIÉN

L<debhelper(7)>

Este programa es parte de debhelper.

=head1 AUTOR

Joey Hess <joeyh@debian.org>

