#!/usr/bin/perl -w

=head1 NAME

dh_auto_build - automatically builds a package

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_auto_build> [S<I<debhelper options>>] [S<B<--> I<params>>]

=head1 DESCRIPTION

dh_auto_build is a debhelper program that tries to automatically
build a package. If a Makefile is found, this is done by running make (or
MAKE, if the environment variable is set).
If there's a setup.py, or Build.PL, it is run to build the package.

This is intended to work for about 90% of packages. If it doesn't work,
you're encoruaged to skip using dh_auto_build at all, and just run the
build process manually.

=head1 OPTIONS

=over 4

=item B<--> I<params>

Pass "params" to the program that is run. These can be used to suppliment
or override any standard parameters that dh_auto_build passes.

=back

=cut

init();

if (-e "Makefile" || -e "makefile" || -e "GNUmakefile") {
	doit(exists $ENV{MAKE} ? $ENV{MAKE} : "make", @{$dh{U_PARAMS}});
}
elsif (-e "setup.py") {
	doit("python", "setup.py", "build", @{$dh{U_PARAMS}});
}
elsif (-e "Build.PL" && -e "Build") {
	doit("perl", "Build", @{$dh{U_PARAMS}});
}

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut
