#!/usr/bin/perl

=head1 NAME

dh_auto_build - automatically builds a package

=cut

use strict;
use warnings;
use Debian::Debhelper::Dh_Buildsystems;

=head1 SYNOPSIS

B<dh_auto_build> [S<I<build system options>>] [S<I<debhelper options>>] [S<B<--> I<params>>]

=head1 DESCRIPTION

B<dh_auto_build> is a debhelper program that tries to automatically build a
package. It does so by running the appropriate command for the build system
it detects the package uses. For example, if a F<Makefile> is found, this is
done by running B<make> (or B<MAKE>, if the environment variable is set). If
there's a F<setup.py>, or F<Build.PL>, it is run to build the package.

This is intended to work for about 90% of packages. If it doesn't work,
you're encouraged to skip using B<dh_auto_build> at all, and just run the
build process manually.

=head1 OPTIONS

See L<debhelper(7)/B<BUILD SYSTEM OPTIONS>> for a list of common build
system selection and control options.

=over 4

=item B<--> I<params>

Pass I<params> to the program that is run, after the parameters that
B<dh_auto_build> usually passes.

=back

=cut

buildsystems_init();
buildsystems_do();

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut

# Local Variables:
# indent-tabs-mode: t
# tab-width: 4
# cperl-indent-level: 4
# End:
