#!/usr/bin/perl -w

=head1 NAME

dh_auto_install - install built files into the temporary directory under debian/

=cut

use strict;
use Debian::Debhelper::Dh_Lib;
use Debian::Debhelper::Dh_Buildsystems;
use Cwd;

=head1 SYNOPSIS

B<dh_auto_install> [S<I<debhelper options>>] [S<I<dh_auto options>>] [S<B<--> I<params>>]

=head1 DESCRIPTION

dh_auto_install is a debhelper program that is responsible for the I<install>
step of the L<dh_auto(7)> building process. dh_auto_install tries to run
original package installation routine to install built files into the proper
places of the file system hierarchy recreated under the (temporary) directory
in debian/.

The files are installed into debian/<package>/ if there is only one binary
package. In the multiple binary package case, the files are instead
installed into debian/tmp/, and should be moved from there to the
appropriate package build directory using L<dh_install(1)> or
L<dh_movefiles(1)>.

If dh_auto_install does not meet your needs or does not work, it is safe to
skip/override it entirely and just run C<make install> or the like manually.

#DH_AUTO SHARED OPTIONS#

=head1 OPTIONS

=over 4

=item B<--> I<params>

Pass "params" to the program that is run. These can be used to supplement
or override the any standard parameters that dh_auto_install passes.

=back

=head1 SUPPORTED BUILD SYSTEMS

#SUPPORTED BUILD SYSTEMS INTRO#
#SUPPORTED BUILD SYSTEMS LIST#

=cut

buildsystems_init();

my $destdir;
my @allpackages=getpackages();
if (@allpackages > 1) {
	$destdir="debian/tmp";
}
else {
	$destdir=tmpdir($dh{MAINPACKAGE});
}
$destdir=cwd()."/".$destdir;

buildsystems_do("install", $destdir);

=head1 SEE ALSO

L<dh_auto(7)>

L<debhelper(7)>

This program is a part of debhelper and its dh_auto package source building
suite.

=head1 AUTHORS

 Joey Hess <joeyh@debian.org>
 Modestas Vainius <modestas@vainius.eu>

=cut
