#!/usr/bin/perl -w

=head1 NAME

dh_auto_build - build package sources

=cut

use strict;
use Debian::Debhelper::Dh_Buildsystems;

=head1 SYNOPSIS

B<dh_auto_build> [S<I<debhelper options>>] [S<I<dh_auto options>>] [S<B<--> I<params>>]

=head1 DESCRIPTION

dh_auto_build is a debhelper program that is responsible for the I<build> step
of the L<dh_auto(7)> building process. Typically, this is the point when
package sources are compiled into binaries or otherwise transformed into ready
to use format. Files produced throughout this step are put to the build
directory.

You can pass additional parameters via I<params>. However, if dh_auto_build
does not meet your needs or does not work, it is safe to skip/override it
entirely and build the package with custom commands.

#DH_AUTO SHARED OPTIONS#

=head1 OPTIONS

=over 4

=item B<--> I<params>

Pass "params" to the program that is run. These can be used to supplement
or override any standard parameters that dh_auto_build passes.

=back

=head1 SUPPORTED BUILD SYSTEMS

#SUPPORTED BUILD SYSTEMS INTRO#
#SUPPORTED BUILD SYSTEMS LIST#

=cut

buildsystems_init();
buildsystems_do();

=head1 SEE ALSO

L<dh_auto(7)>

L<debhelper(7)>

This program is a part of debhelper and its dh_auto package source building
suite.

=head1 AUTHOR

 Joey Hess <joeyh@debian.org>
 Modestas Vainius <modestas@vainius.eu>

=cut
