#!/usr/bin/perl -w

=head1 NAME

dh_builddeb - build debian packages

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_builddeb> [S<I<debhelper options>>] [B<--destdir=>I<directory>] [B<name=>I<filename>] [S<B<--> I<params>>]

=head1 DESCRIPTION

dh_builddeb simply calls L<dpkg(8)> to build a debian package or
packages.

=head1 OPTIONS

=over 4

=item B<--destdir=>I<directory>

Use this if you want the generated .deb files to be put in a directory
other than the default of ".."

=item B<--name=>I<filename>

Use this if you want to force the generated .deb file to have a particular
file name. Does not work well if more than one .deb is generated!

=item B<-u>I<params>

=item B<--> I<params>

Pass I<params> to L<dpkg(1)|dpkg> when it is used to build the
package.

=back

=cut

init();

# Set the default destination directory.
if (! defined $dh{DESTDIR}) {
	$dh{DESTDIR}='..';
}

if (! defined $dh{FILENAME}) {
	$dh{FILENAME}='';
}
else {
	$dh{FILENAME}="/$dh{FILENAME}";
}

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	doit("dpkg","--build",$tmp,"$dh{DESTDIR}$dh{FILENAME}",@{$dh{U_PARAMS}});
}

=head1 SEE ALSO

L<debhelper(1)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut
