.TH DH_BUILDDEB 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_builddeb \- build debian packages
.SH SYNOPSIS
.B dh_builddeb
.I "[debhelper options] [--destdir=directory] [-uparams] [-- params]"
.SH "DESCRIPTION"
dh_builddeb simply calls
.BR dpkg (8)
to build a .deb package or packages.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B --destdir=directory
Use this if you want the generated .deb files to be put in a directory other
than the default of ".."
.TP
.B \-uparams
.TP
.B \-\- params
Pass "params" to 
.BR dpkg-deb (1)
when it is used to build the package.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
