#!/usr/bin/perl -w
#
# Build the .deb package, assuming all the files are set up.

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	doit("dpkg","--build",$TMP,"..");
}
