.TH DH_BUILDDEB 1
.SH NAME
dh_builddeb \- build debian packages
.SH SYNOPSIS
.B dh_builddeb
.I "[-v] [-a] [-i] [--no-act] [-ppackage] [-Ptmpdir]"
.SH "DESCRIPTION"
dh_builddeb simply calls
.BR dpkg (8)
to build a .deb package or packages.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory, etc.
.TP
.B \-a, \--arch
Build all architecture dependent packages.
.TP
.B \-i, \--indep
Build all architecture independent packages.
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B -ppackage, \--package=package
Build the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory.
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be built.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
