.TH DH_CLEAN 1
.SH NAME
dh_clean \- clean up package build directories
.SH SYNOPSIS
.B dh_clean
.I "[-v] [-a] [-i] [-k] [-ppackage] [-Ptmpdir] [file ...]"
.SH "DESCRIPTION"
dh_clean is a debhelper program that is responsible for cleaning up after a
package is built. It removes the package build directories, and removes some
other files, such as debian/substvars, debian/files, DEADJOE, emacs backup 
files, etc.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Clean up the package build directory for all architecture dependent packages.
.TP
.B \-i, \--indep
Clean up the package build directory for all architecture independent packages.
.TP
.B \-ppackage, \--package=package
Clean up the package build directory for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory.
.TP
.B \-k, \--keep
Do not delete debian/files. When do you want to use this? Anytime you have a
debian/rules that has 2 binary targets that build different .deb packages;
for example, one target is binary-arch, and the other is binary-indep, or
one target builds the shared library, and the other the -dev package. If you
didn't use -k in these cases, then debian/files would be deleted in the
middle, and your changes file will only contain the last binary package that
was built.
.TP
.B file ...
Delete these files too.
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will have their package build directories cleaned up.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH BUGS
Filenames with spaces in them will not currently be deleted when specified
as parameters.
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
