.TH DH_CLEAN 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_clean \- clean up package build directories
.SH SYNOPSIS
.B dh_clean
.I "[debhelper options] [-k] [-d] [file ...]"
.SH "DESCRIPTION"
dh_clean is a debhelper program that is responsible for cleaning up after a
package is built. It removes the package build directories, and removes some
other files, such as debian/substvars, debian/files, DEADJOE, emacs backup 
files, any detritus left behind by other debhelper commands, etc.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-k, \--keep
Do not delete debian/files. When do you want to use this? Anytime you have a
debian/rules that has 2 binary targets that build different .deb packages;
for example, one target is binary-arch, and the other is binary-indep, or
one target builds the shared library, and the other the -dev package. If you
didn't use -k in these cases, then debian/files would be deleted in the
middle, and your changes file will only contain the last binary package that
was built.
.TP
.B \-d, \--dirs-only
Only clean the package build directories, do not clean up any other files at
all.
.TP
.B file ...
Delete these files too.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
