.TH DH_DU 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_du \- generate DEBIAN/du file (deprecated)
.SH SYNOPSIS
.B dh_du
.SH "DESCRIPTION"
dh_du is a debhelper program that was responsible for generating
a DEBIAN/du file, which listed the disk usage of directories in the package.
.P
This program is now deprecated, and does nothing, after a decision by the
debian developers that du control files should not exit. It will simply
output a warning message now.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@debian.org>
