.TH DH_DU 1
.SH NAME
dh_du \- generate DEBIAN/du file
.SH SYNOPSIS
.B dh_du
.I "[-v] [-a] [-i] [-ppackage] [-Ptmpdir]"
.SH "DESCRIPTION"
dh_du is a debhelper program that is responsible for generating
a DEBIAN/du file, which lists the disk usage of directories in the package.
This file isn't used by anything yet, but it could be helpful for a future
debian installer program.
.P
The du file is installed with proper permissions and ownerships.
.SH OPTIONS
.TP
.B \-v
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a
Generate du files for all architecture dependent packages.
.TP
.B \-i
Generate du files for all architecture independent packages.
.TP
.B \-ppackage
Generate du file for the package named "package".
.TP
.B \-Ptmpdir
Use "tmpdir" for package build directory. 
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
