#!/bin/sh -e
#
# Generate a DEBIAN/du file, that lists the disk usage of the directories in 
# the package.
#
# No longer - it was decided these files are a bad idea.

echo "dh_du: this program does nothing and is deprecated. Remove it from debian/rules." >&2
