#!/usr/bin/perl -w
#
# Generate a DEBIAN/du file, that lists the disk usage of the directories in 
# the package.
#
# No longer - it was decided these files are a bad idea.

BEGIN { push @INC, "debian", "/usr/share/debhelper" }
use Dh_Lib;

warning("this program does nothing and is deprecated. Remove it from debian/rules.");
