#!/usr/bin/perl -w

=head1 NAME

dh_desktop - deprecated no-op

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_desktop> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_desktop> was a debhelper program that registers F<.desktop> files.
However, it no longer does anything, and is now deprecated.

If a package ships F<desktop> files, they just need to be installed in the
correct location (F</usr/share/applications>) and they will be registered by
the appropriate tools for the corresponding desktop environments.

=cut

init();

warning("This program is deprecated, and does nothing anymore.");

=head1 SEE ALSO

L<debhelper>

This program is a part of debhelper.

=head1 AUTHOR

Ross Burton <ross@burtonini.com>

=cut
