#!/usr/bin/perl -w
#
# Do some general file permission fixups.

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);

	# General permissions fixing.
	if (! defined($dh{EXCLUDE_FIND}) || $dh{EXCLUDE_FIND} eq '') {
		# It's much faster to do it this way, but we can only do
		# this if there is nothing to exclude.
		if (-d $TMP) {
			doit("chown","-R","root.root",$TMP);
			doit("chmod","-R","go=rX,u+rw,a-s",$TMP);
		}

		$find_options="";
	}
	else {
		# Do it the hard way.
		complex_doit("find $TMP ! \\( $dh{EXCLUDE_FIND} \\) -print0 \
			2>/dev/null | xargs -0r chown root.root");
		complex_doit("find $TMP ! \\( $dh{EXCLUDE_FIND} \\) -print0 \
			2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s");

		$find_options="! \\( $dh{EXCLUDE_FIND} \\)";
	}

	# Fix up premissions in usr/doc, setting everything to not exectable
	# by default, but leave examples directories alone.
	complex_doit("find $TMP/usr/doc -type f $find_options ! -regex '.*/examples/.*' -print0",
		"2>/dev/null | xargs -0r chmod 644");
	complex_doit("find $TMP/usr/doc -type d $find_options -print0",
		"2>/dev/null | xargs -0r chmod 755");

	# Executable man pages are a bad thing..
	complex_doit("find $TMP/usr/man/ $TMP/usr/X11*/man/ -type f",
		"$find_options -print0 2>/dev/null | xargs -0r chmod 644");

	# ..and so are executable shared and static libraries 
	# (and .la files from libtool)
	complex_doit("find $TMP -perm -5 -type f",
		"\\( -name '*.so*' -or -name '*.la' -or -name '*.a' \\) $find_options -print0",
		"2>/dev/null | xargs -0r chmod a-X");
}
