.TH DH_FIXPERMS 1
.SH NAME
dh_fixperms \- fix permissions of files in package build directories
.SH SYNOPSIS
.B dh_fixperms
.I "[-v] [-a] [-i] [-ppackage] [-Ptmpdir]"
.SH "DESCRIPTION"
dh_fixperms is a debhelper program that is responsible for setting the
permissions of files in package build directories to a sane state.
.P
dh_fixperms makes all files in usr/doc in the package build directory
(excluding files in the examples/ directory) be mode 644. It also changes 
the permissions of all man pages to mode 644. It makes all files be owned by 
root, and it removes group and other write permission from all files.
.SH OPTIONS
.TP
.B \-v
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a
Fix permissions for all architecture dependent packages.
.TP
.B \-i
Fix permissions for all architecture independent packages.
.TP
.B \-ppackage
Fix permissions for the package named "package".
.TP
.B \-Ptmpdir
Use "tmpdir" for package build directory. 
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will have their permissions fixed.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
