.TH DH_INSTALLDEBFILES 1
.SH NAME
dh_gencontrol \- generate and install control file
.SH SYNOPSIS
.B dh_gencontrol
.I "[-v] [-a] [-i] [-ppackage] [-Ptmpdir] [-uparams]"
.SH "DESCRIPTION"
dh_gencontrol is a debhelper program that is responsible for generating and
installing control files, and installing them into the DEBIAN directory with
the proper permissions.
.P
This program is merely a wrapper around
.BR dpkg-gencontrol (1)
You may prefer to simply run
.BR dpkg-gencontrol (1)
by hand.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Install files for all architecture dependent packages.
.TP
.B \-i, \--indep
Install files for all architecture independent packages.
.TP
.B \-ppackage, \--package=package
Install files for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-uparams, \--update-rcd-params=params
Pass "params" to 
.BR dpkg-gencontrol (1)
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.BR dpkg-shlibdeps (1)
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
