#!/usr/bin/perl -w
#
# Generate and install the control file. Simple dpkg-gencontrol wrapper.

BEGIN { push @INC, "debian", "/usr/share/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	$EXT=pkgext($PACKAGE);
	
	$changelog=pkgfile($PACKAGE,'changelog');
	if (! $changelog) {
		$changelog='debian/changelog';
	}

	if ( ! -d '$TMP/DEBIAN' ) {
		doit("install","-o","root","-g","root","-d","$TMP/DEBIAN");
	}

	# Generate and install control file.
	doit("dpkg-gencontrol","-l$changelog","-isp","-p$PACKAGE",
		"-Tdebian/$EXT\substvars","-P$TMP",@{$dh{U_PARAMS}});

	# This chmod is only necessary if the user sets the umask to something odd.
	doit("chmod","644","$TMP/DEBIAN/control");
	
	doit("chown","root.root","$TMP/DEBIAN/control");
}
