#!/usr/bin/perl -w
#
# Integration with xaw-wrappers
#
# If debian/xaw-wrappers file exists, save it to 
# $tmp/usr/share/xaw-wrappers/config/$package
#
# Also, add calls to postinst and postrm.

use strict;
use Debian::Debhelper::Dh_Lib;
init();

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $xaw=pkgfile($package,'xaw');

	if ($xaw ne '') {
		if (! -d "$tmp/usr/share/xaw-wrappers/config") {
			doit("install","-d","$tmp/usr/share/xaw-wrappers/config");
		}
		doit("install","-p","-m644",$xaw,
			"$tmp/usr/share/xaw-wrappers/config/$package");

		if (! $dh{NOSCRIPTS}) {
			# Parse the xaw conf file to figure out what programs
			# and link names are present in it. Have to pass
			# those into the scripts.
			my %data;
			my $install_opts='';
			my $remove_opts='';
			my $stanza='';
			
			open (IN,$xaw);
			while (<IN>) {
				chomp;
				s/\s+/ /g;
				if (/^#/ eq '') {
					if (/(.*?):\s?(.*)/) {
						$data{lc($1)}=$2;
						$stanza=1;
					}
					elsif ($stanza) {
						$install_opts.="'$data{program} $data{'link-name'} $data{wrapped}' ";
						$remove_opts.="'$data{'link-name'} $data{wrapped}' ";
						undef %data;
						$stanza='';
					}
				}
			}
			close IN;

			if ($stanza) {
				$install_opts.="'$data{program} $data{'link-name'} $data{wrapped}'";
				$remove_opts.="'$data{'link-name'} $data{wrapped}'";
			}
			
			autoscript($package,"postinst","postinst-xaw",
				"s:#OPTS#:$install_opts:");
			autoscript($package,"prerm","prerm-xaw",
				"s:#OPTS#:$remove_opts:");
			autoscript($package,"postrm","postrm-xaw");
		}
	}
}
