#!/usr/bin/perl -w
#
# Integration with debian pam system:
#
# If debian/pam file exists, save it to $tmp/etc/pam.d/$package

use strict;
use Debian::Debhelper::Dh_Lib;
init();

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $pam=pkgfile($package,"pam");
	
	if ($pam ne '') {
		if (! -d "$tmp/etc/pam.d") {
			doit("install","-d","$tmp/etc/pam.d");
		}
		doit("install","-p","-m644",$pam,"$tmp/etc/pam.d/$package");
	}
}
