#!/usr/bin/perl -w
#
# Reads debian/examples, installs all files listed there into
# /usr/share/doc/$package/examples

use strict;
use Debian::Debhelper::Dh_Lib;
init();

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $file=pkgfile($package,"examples");
	
	my @examples;
	
	if ($file) {
		@examples=filearray($file, ".");
	}	

	if (($package eq $dh{FIRSTPACKAGE} || $dh{PARAMS_ALL}) && @ARGV) {
		push @examples, @ARGV;
	}

	if (@examples) {
		if (! -d "$tmp/usr/share/doc/$package/examples") {
			doit("install","-d","$tmp/usr/share/doc/$package/examples");
		}
		
		doit("cp","-a",@examples,"$tmp/usr/share/doc/$package/examples");
	}
}
