#!/usr/bin/perl -w
#
# Registration with emacsen-common.

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);

	$emacsen_install=pkgfile($PACKAGE,"emacsen-install");
	$emacsen_remove=pkgfile($PACKAGE,"emacsen-remove");

	if ($emacsen_install ne '') {
		if (! -d "$TMP/usr/lib/emacsen-common/packages/install") {
			doit("install","-d","$TMP/usr/lib/emacsen-common/packages/install");
		}
		doit("install",$emacsen_install,"$TMP/usr/lib/emacsen-common/packages/install/$PACKAGE");
	}

	if ($emacsen_remove ne '') {
		if (! -d "$TMP/usr/lib/emacsen-common/packages/remove") {
			doit("install","-d","$TMP/usr/lib/emacsen-common/packages/remove");
		}
		doit("install","$emacsen_remove","$TMP/usr/lib/emacsen-common/packages/remove/$PACKAGE");
	}

	if ($emacsen_install ne '' || $emacsen_remove ne '') {
		if (! $dh{NOSCRIPTS}) {
			autoscript($PACKAGE,"postinst","postinst-emacsen",
				"s/#PACKAGE#/$PACKAGE/");
			autoscript($PACKAGE,"prerm","prerm-emacsen",
				"s/#PACKAGE#/$PACKAGE/");
		}
	}
}
