.TH DH_INSTALLDIRS 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installdirs \- create subdirectories in package build directories
.SH SYNOPSIS
.B dh_installdirs
.I "[debhelper options] [-A] [dir ...]"
.SH "DESCRIPTION"
dh_installdirs is a debhelper program that is responsible for creating
subdirectories in package build directories.
.P
Any directory names specified as parameters will be created in the package
build directory of the first package dh_installdirs is told to act on. By
default, this is the first binary package in debian/control, but if you use
-p, -i, or -a flags, it will be the first package specified by those flags.
.P
A file named debian/package.dirs can list other directories to be created.
Separate the directory names with whitespace.
.P
Be sure to only use directory names relative to the package build
directory. Ie, "/usr/bin" should not be used, use "usr/bin" instead.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-A, \--all
Create any directories specified by command line parameters in ALL packages
acted on, not just the first.
.TP
.B dir ...
Create these directories in the package build directory of the first package
acted on. (Or in all packages if -A is specified.)
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH BUGS
It's impossible to specify filenames with spaces or other whitespace in them
in debian/package.dirs file. This is more a historical design flaw than a bug.
.SH AUTHOR
Joey Hess <joeyh@debian.org>
