#!/usr/bin/perl -w
#
# Install files from debian/ into the package's DEBIAN directory.

use Debian::Debhelper::Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	$EXT=pkgext($PACKAGE);

	if (! -d "$TMP/DEBIAN") {
		doit("install","-o",0,"-g",0,"-d","$TMP/DEBIAN");
	}

	# Install debian install scripts.
	# If any .debhelper files exist, add them into the scripts.
	foreach $file (qw{postinst preinst prerm postrm}) {
		$f=pkgfile($PACKAGE,$file);
		if ($f) {
			if (-f "debian/$EXT$file.debhelper") {
				# Add this into the script, where it has
				# #DEBHELPER#
				# TODO: do internally, no perl fork?
				complex_doit("perl -pe 's~#DEBHELPER#~qx{cat debian/$EXT$file.debhelper}~eg' < $f > $TMP/DEBIAN/$file");
		        }
			else {
				# Just get rid of any #DEBHELPER# in the 
				# script.
				complex_doit("sed s/#DEBHELPER#// < $f > $TMP/DEBIAN/$file");
			}
			doit("chown","0.0","$TMP/DEBIAN/$file");
			doit("chmod",755,"$TMP/DEBIAN/$file");
		}
		else {
			# Auto-generate script header and add .debhelper
			# content to it.
			if (-f "debian/$EXT$file.debhelper") {
				complex_doit("echo '#!/bin/sh -e' > $TMP/DEBIAN/$file");
				complex_doit("cat debian/$EXT$file.debhelper >> $TMP/DEBIAN/$file");
				doit("chown","0.0","$TMP/DEBIAN/$file");
				doit("chmod",755,"$TMP/DEBIAN/$file");
			}
		}
	}

	# Install non-executable files
	foreach $file (qw{shlibs conffiles}) {
		$f=pkgfile($PACKAGE,$file);
		if ($f) {
			doit("install","-o",0,"-g",0,"-m",644,"-p",$f,"$TMP/DEBIAN/$file");
		}
	}
}
