#!/usr/bin/perl -w
#
# Add to postinst and prerm to register a window manager.

use strict;
use Debian::Debhelper::Dh_Lib;
init();

if (! defined $dh{PRIORITY}) {
        $dh{PRIORITY}=20;
}

if (@ARGV) {
	# This is here for backwards compatability. If the filename doesn't
	# include a path, assume it's in /usr/X11R6/bin.
	if ($ARGV[0] !~ m:/:) {
		$ARGV[0]="/usr/X11R6/bin/$ARGV[0]";
	}
}

foreach my $package (@{$dh{DOPACKAGES}}) {
#	my $tmp=tmpdir($package);
	my $file=pkgfile($package,"wm");

	my @wm;
	if ($file) {
		@wm=filearray($file, '.');
	}

	if (($package eq $dh{FIRSTPACKAGE} || $dh{PARAMS_ALL}) && @ARGV) {
		push @wm, @ARGV;
	}

	if (@wm && ! $dh{NOSCRIPTS}) {
		foreach (@wm) {
			autoscript($package,"postinst","postinst-wm","s:#WM#:$_:;s/#PRIORITY#/$dh{PRIORITY}/",);
			autoscript($package,"prerm","prerm-wm","s:#WM#:$_:");
		}
	}
}

