#!/usr/bin/perl -w

=head1 NAME

dh_installlogrotate - install logrotate config files

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_installlogrotate> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_installlogrotate is a debhelper program that is responsible for installing
logrotate config files into etc/logrotate.d in package build directories.
Files named debian/package.logrotate are installed.

=cut

init();

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $file=pkgfile($package,"logrotate");

	if ($file) {
		if (! -d "$tmp/etc/logrotate.d") {
			doit("install","-o",0,"-g",0,"-d","$tmp/etc/logrotate.d");
		}
		doit("install","-m",644,$file,"$tmp/etc/logrotate.d/$package");
	}
}

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut
