.TH DH_INSTALLPAM 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installpam \- install pam support files
.SH SYNOPSIS
.B dh_installpam
.I "[debhelper options] [-n]"
.SH "DESCRIPTION"
dh_installpam is a debhelper program that is responsible for installing
files used by PAM into package build directories. 
.P
If a file named debian/package.pam exists, then it is installed into
etc/pam.d/package in the package build directory.
.P
For the first first binary package listed in the control file, you may use
debian/pam instead.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.TP
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
