#!/bin/sh -e
#
# This program is deprecated, but left in the package for backwards
# compatability. It simply calls the 3 programs that replaced it.

PATH=debian:$PATH:/usr/lib/debhelper

warn "Note: use of this program is deprecated."

dh_installdeb $*
dh_shlibdeps $*
dh_gencontrol $*
