#!/usr/bin/perl

=head1 NAME

dh_installlogrotate - install logrotate config files

=cut

use strict;
use warnings;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_installlogrotate> [S<I<debhelper options>>] [B<--name=>I<name>]

=head1 DESCRIPTION

B<dh_installlogrotate> is a debhelper program that is responsible for installing
logrotate config files into F<etc/logrotate.d> in package build directories.
Files named F<debian/package.logrotate> are installed.

=head1 OPTIONS

=over 4

=item B<--name=>I<name>

Look for files named F<debian/package.name.logrotate> and install them as
F<etc/logrotate.d/name>, instead of using the usual files and installing them
as the package name.

=back

=cut

init();

# PROMISE: DH NOOP WITHOUT logrotate

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $file=pkgfile($package,"logrotate");

	if ($file) {
		install_dir("$tmp/etc/logrotate.d");
		install_file($file,"$tmp/etc/logrotate.d/".pkgfilename($package));
	}
}

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut

# Local Variables:
# indent-tabs-mode: t
# tab-width: 4
# cperl-indent-level: 4
# End:
