#!/bin/sh -e
#
# This program is deprecated, but left in the package for backwards
# compatability. It simply calls the 3 programs that replaced it.

PATH=debian:$PATH:/usr/lib/debhelper

echo "* Note: dh_installdebfiles is deprecated." >&2

dh_installdeb $*
dh_shlibdeps $*
dh_gencontrol $*
