#!/usr/bin/perl -w
#
# Add to postinst and postrm to register a window manager.

BEGIN { push @INC, "debian", "/usr/share/debhelper" }
use Dh_Lib;
init();

$wm=shift;

if ($wm eq '') {
	error("No window manager filename was specified.");
}

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
#	$TMP=tmpdir($PACKAGE);

	if (! $dh{NOSCRIPTS}) {
		autoscript($PACKAGE,"postinst","postinst-wm","s:#WM#:$wm:");
		autoscript($PACKAGE,"postrm","postrm-wm","s:#WM#:$wm:");
	}
}
