#!/bin/sh -e
#
# Install files from debian/ into the package's DEBIAN directory.
# Also generates the control file.

PATH=debian:$PATH:/usr/lib/debhelper
. dh_lib

for PACKAGE in $DH_DOPACKAGES; do
	TMP=`tmpdir $PACKAGE`
	EXT=`pkgext $PACKAGE`

	if [ ! -d $TMP/DEBIAN ]; then
		doit "install -o root -g root -d $TMP/DEBIAN"
	fi

	# Install debian install scripts.
	# If any .debhelper files exist, add them into the scripts.
	for file in postinst preinst prerm postrm; do
		if [ -f debian/$EXT$file ]; then
			# Add this into the script, where it has #DEBHELPER#
			if [ -f debian/$EXT$file.debhelper ]; then
				doit "perl -pe 's~#DEBHELPER#~qx{cat debian/$EXT$file.debhelper}~eg' < debian/$EXT$file > $TMP/DEBIAN/$file"
				doit "chown root.root $TMP/DEBIAN/$file"
				doit "chmod 755 $TMP/DEBIAN/$file"
			else
				doit "install -o root -g root -p debian/$EXT$file $TMP/DEBIAN/$file"
			fi
		else
			# Auto-generate script header and add .debhelper
			# content to it.
			if [ -f debian/$EXT$file.debhelper ]; then
				doit "echo '#!/bin/sh -e' > $TMP/DEBIAN/$file"
				doit "cat debian/$EXT$file.debhelper >> $TMP/DEBIAN/$file"
				doit "chown root.root $TMP/DEBIAN/$file"
				doit "chmod 755 $TMP/DEBIAN/$file"
			fi
		fi
	done

	# Install non-executable files
	for file in shlibs conffiles; do
		if [ -f debian/$EXT$file ]; then
			doit "install -o root -g root -m 644 -p debian/$EXT$file $TMP/DEBIAN/$file"
		fi                                               
	done

	# Run dpkg-shlibdeps to generate dependancies.
	filelist=""
	for file in `find $TMP -type f \( -perm +111 -or -name "*.so*" \) | tr "\n" " "` ; do
		case "`file $file`" in
			*ELF*)
				filelist="$file $filelist"
			;;
		esac
	done
	if [ "$filelist" ]; then
		doit "dpkg-shlibdeps -Tdebian/${EXT}substvars $filelist"
	fi

	# Generate and install control file.
	doit "dpkg-gencontrol -p$PACKAGE -Tdebian/${EXT}substvars -P$TMP"
	doit "chown root.root $TMP/DEBIAN/control"
done
