#!/usr/bin/perl -w
#
# Install files from debian/ into the package's DEBIAN directory.

use strict;
use Debian::Debhelper::Dh_Lib;
init();

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $ext=pkgext($package);

	if (! -d "$tmp/DEBIAN") {
		doit("install","-o",0,"-g",0,"-d","$tmp/DEBIAN");
	}

	# Install debian install scripts.
	# If any .debhelper files exist, add them into the scripts.
	foreach my $file (qw{postinst preinst prerm postrm}) {
		my $f=pkgfile($package,$file);
		if ($f) {
			if (-f "debian/$ext$file.debhelper") {
				# Add this into the script, where it has
				# #DEBHELPER#
				# TODO: do internally, no perl fork?
				complex_doit("perl -pe 's~#DEBHELPER#~qx{cat debian/$ext$file.debhelper}~eg' < $f > $tmp/DEBIAN/$file");
		        }
			else {
				# Just get rid of any #DEBHELPER# in the 
				# script.
				complex_doit("sed s/#DEBHELPER#// < $f > $tmp/DEBIAN/$file");
			}
			doit("chown","0.0","$tmp/DEBIAN/$file");
			doit("chmod",755,"$tmp/DEBIAN/$file");
		}
		else {
			# Auto-generate script header and add .debhelper
			# content to it.
			if (-f "debian/$ext$file.debhelper") {
				complex_doit("echo '#!/bin/sh -e' > $tmp/DEBIAN/$file");
				complex_doit("cat debian/$ext$file.debhelper >> $tmp/DEBIAN/$file");
				doit("chown","0.0","$tmp/DEBIAN/$file");
				doit("chmod",755,"$tmp/DEBIAN/$file");
			}
		}
	}

	# Install non-executable files
	foreach my $file (qw{shlibs conffiles}) {
		my $f=pkgfile($package,$file);
		if ($f) {
			doit("install","-o",0,"-g",0,"-m",644,"-p",$f,"$tmp/DEBIAN/$file");
		}
	}

	# Automatic conffiles registration: If it is in /etc, it is a
	# conffile.
	if (! compat(2) && -d "$tmp/etc") {
		complex_doit("find $tmp/etc -type f |sed 's~^$tmp~~' >> $tmp/DEBIAN/conffiles");
		# Anything found?
		if (-z "$tmp/DEBIAN/conffiles") {
			doit("rm", "-f", "$tmp/DEBIAN/conffiles");
		}
		else {
			doit("chmod", 644, "$tmp/DEBIAN/conffiles");
		}
	}
}
