#!/usr/bin/perl -w
#
# Install cron scripts into the appropriate places.

use Debian::Debhelper::Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	foreach $type (qw{daily weekly monthly}) {
		$cron=pkgfile($PACKAGE,"cron.$type");
		if ($cron) {
			if (! -d "$TMP/etc/cron.$type") {
				doit("install","-o","root","-g","root","-d","$TMP/etc/cron.$type");
			}
			doit("install",$cron,"$TMP/etc/cron.$type/$PACKAGE");
		}
	}
	# Seperate because this needs to be mode 644.
	$cron=pkgfile($PACKAGE,"cron.d");
	if ($cron) {
		if (! -d "$TMP/etc/cron.d") {
			doit("install","-o","root","-g","root","-d","$TMP/etc/cron.d");
		}	
		doit("install","-m",644,$cron,"$TMP/etc/cron.d/$PACKAGE");
	}
}
