.TH DH_INSTALLXFONTS 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installxfonts \- register X fonts
.SH SYNOPSIS
.B dh_installxfonts
.I "[debhelper options]"
.SH "DESCRIPTION"
dh_installxfonts is a debhelper program that is responsible for
registering X fonts, so their corresponding fonts.dir, fonts.alias,
and fonts.scale be rebuilt properly at install time.
.P
Before calling this program, you should have installed any X fonts
provided by your package into the appropriate location in the package build
directory. Also, your package should depend on xbase-clients (>= 3.3.3.1-5).
.P
It automatically generates the postinst and postrm commands needed to
register X fonts.  See
.BR dh_installdeb (1)
for an explanation of how this works.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.SH NOTES
See
.BR update-fonts-alias (8)
,
.BR update-fonts-scale (8)
and
.BR mkfontdir (1x)
for more information about X font installation.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.BR update-fonts-alias (8)
.BR update-fonts-scale (8)
.SH AUTHOR
Changwoo Ryu <cwryu@debian.org>
