.TH DH_INSTALLDEBFILES 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installdebfiles \- install files into the DEBIAN directory
.SH SYNOPSIS
.B dh_installdebfiles
.SH "DESCRIPTION"
dh_installdebfiles is a debhelper program that is responsible for installing
files into the DEBIAN directory in package build directories with the
correct permissions, canculating shared library dependancies, and creating a
control file.
.P
This program is deprecated. It is now merely a wrapper around three other
programs, and you may replace any calls to this program by:
.P
  dh_installdeb
  dh_shlibdeps
  dh_gencontrol
.SH WARNING
This program will be removed at some time in the future.
.SH OPTIONS
Any options passed to this program will be sent to each of the 3 programs
listed above.
.SH "SEE ALSO"
.TP
.BR debhelper (1)
.TP
.BR dh_installdeb (1)
.TP
.BR dh_shlibdeps (1)
.TP
.BR dh_gencontrol (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
