#!/usr/bin/perl -w

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	$mime=pkgfile($PACKAGE,"mime");
	
	if ($mime ne '') {
		if (! -d "$TMP/usr/lib/mime/packages") {
			doit("install","-d","$TMP/usr/lib/mime/packages");
		}
		doit("install","-p","-m644",$mime,"$TMP/usr/lib/mime/packages/$PACKAGE");

		if (! $dh{NOSCRIPTS}) {
			autoscript($PACKAGE,"postinst","postinst-mime");
			autoscript($PACKAGE,"postrm","postrm-mime")
		}
	}
}
