.TH DH_INSTALLDIRS 1
.SH NAME
dh_installdirs \- create subdirectories in package build directories
.SH SYNOPSIS
.B dh_installdirs
.I "[-v] [-a] [-i] [--no-act] [-ppackage] [-Ptmpdir] [-A] [dir ...]"
.SH "DESCRIPTION"
dh_installdirs is a debhelper program that is responsible for creating
subdirectories in package build directories.
.P
Any directory names specified as parameters will be created in the package
build directory of the first package dh_installdirs is told to act on. By
default, this is the first binary package in debian/control, but if you use 
-p, -i, or -a flags, it will be the first package specified by those flags.
.P
A file named debian/package.dirs (debian/dirs may be used for the first
binary package in debian/control) can list other directories to be created.
Separate the directory names with whitespace.
.P
Be sure to only use directory names relative to the package build
directory. Ie, "/usr/bin" should not be used, use "usr/bin" instead.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Create directories for all architecture dependent packages.
.TP
.B \-i, \--indep
Create directories for all architecture independent packages.
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B \-ppackage, \--package=package
Create directories for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-A, \--all
Create any directories specified by command line parameters in ALL packages
acted on.
.TP
.B dir ...
Create these directories in the package build directory of the first package
acted on. (Or in all packages if -A is specified.)
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH BUGS
Directories with spaces in them will not currently be installed.
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
