#!/usr/bin/perl -w
#
# Reads debian/examples, installs all files listed there into
# /usr/doc/$PACKAGE/examples

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);
	$file=pkgfile($PACKAGE,"examples");
	
	undef @examples;
	
	if ($file) {
		@examples=filearray($file);
	}	

	if (($PACKAGE eq $dh{FIRSTPACKAGE} || $dh{PARAMS_ALL}) && @ARGV) {
		push @examples, @ARGV;
	}

	if (@examples) {
		if (! -d "$TMP/usr/doc/$PACKAGE/examples") {
			doit("install","-d","$TMP/usr/doc/$PACKAGE/examples");
		}
		
		doit("cp","-a",@examples,"$TMP/usr/doc/$PACKAGE/examples");
	}
}
