.TH DH_INSTALLCHANGELOGS 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installchangelogs \- install changelogs into package build directories
.SH SYNOPSIS
.B dh_installchangelogs
.I "[debhelper options] [-k] [upstream]"
.SH "DESCRIPTION"
dh_installchangelogs is a debhelper program that is responsible for installing
changelogs into package build directories.
.P
dh_installchangelogs determines if the package is a debian native package,
and if so, it installs debian/changelog into usr/share/doc/package/changelog
in the package build directory. Otherwise, it installs debian/changelog into
usr/share/doc/package/changelog.Debian in the package build directory. (If
files named debian/package.changelog exist, they will be used in preference to
debian/changelog.)
.P
If an upstream changelog file is specified as an option, and the package is
not a native debian package, then this upstream changelog will be installed
as usr/share/doc/package/changelog in the package build directory. If the
changelog is a html file (determined by file extention), it will be
installed as usr/share/doc/package/changelog.html instead (with a link to
usr/share/doc/package/changelog).
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-k, \--keep
Keep the original name of the upstream changelog. This will be accomplished
by installing the upstream changelog as "changelog", and making a symlink from
that to the original name of the changelog file. This can be useful if the
upstream changelog has an unusual name, or if other documentation in the
package refers to the changelog file.
.TP
.B upstream
Install this file as the upstream changelog.
.SH NOTES
It is an error to specify an upstream changelog file for a debian native
package.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@debian.org>
