#!/usr/bin/perl -w
#
# Registration with emacsen-common.

BEGIN { push @INC, "debian", "/usr/share/debhelper" }
use Dh_Lib;
init();

if (! defined $dh{number}) {
	$dh{number}=50;
}
if (! defined $dh{flavor}) {
	$dh{flavor}='emacs';
}

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);

	$emacsen_install=pkgfile($PACKAGE,"emacsen-install");
	$emacsen_remove=pkgfile($PACKAGE,"emacsen-remove");
	$emacsen_startup=pkgfile($PACKAGE,"emacsen-startup");

	if ($emacsen_install ne '') {
		if (! -d "$TMP/usr/lib/emacsen-common/packages/install") {
			doit("install","-d","$TMP/usr/lib/emacsen-common/packages/install");
		}
		doit("install","-m0755",$emacsen_install,"$TMP/usr/lib/emacsen-common/packages/install/$PACKAGE");
	}

	if ($emacsen_remove ne '') {
		if (! -d "$TMP/usr/lib/emacsen-common/packages/remove") {
			doit("install","-d","$TMP/usr/lib/emacsen-common/packages/remove");
		}
		doit("install","-m0755","$emacsen_remove","$TMP/usr/lib/emacsen-common/packages/remove/$PACKAGE");
	}
	
	if ($emacsen_startup ne '') {
		if (! -d "$TMP/etc/$dh{flavor}/site-start.d/") {
			doit("install","-d","$TMP/etc/$dh{flavor}/site-start.d/");
		}
		doit("install","-m0644",$emacsen_startup,"$TMP/etc/$dh{flavor}/site-start.d/$dh{number}$PACKAGE.el");
	}

	if ($emacsen_install ne '' || $emacsen_remove ne '') {
		if (! $dh{NOSCRIPTS}) {
			autoscript($PACKAGE,"postinst","postinst-emacsen",
				"s/#PACKAGE#/$PACKAGE/");
			autoscript($PACKAGE,"prerm","prerm-emacsen",
				"s/#PACKAGE#/$PACKAGE/");
		}
	}
}	
