.TH DH_INSTALLLOGROTATE 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installlogrotate \- install logrotate config files
.SH SYNOPSIS
.B dh_logrotate
.I "[debhelper options]"
.SH "DESCRIPTION"
dh_installlogrotate is a debhelper program that is responsible for installing
logrotate config files into etc/logrotate.d in package build directories.
Files named debian/package.logrotate are installed.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@debian.org>
