.TH DH_INSTALLDOCS 1
.SH NAME
dh_installdocs \- install documentation into package build directories
.SH SYNOPSIS
.B dh_installdocs
.I "[-v] [-a] [-i] [--no-act] [-ppackage] [-Ptmpdir] [-A] [file ...]"
.SH "DESCRIPTION"
dh_installdocs is a debhelper program that is responsible for installing
documentation into usr/doc/package in package build directories.
.P
dh_installdocs automatically installs debian/copyright if it exists. If
dh_installdocs is acting on multiple packages, debian/copyright files will be
installed into all packages. However, if you need to have seperate copyright
files for different binary packages, you can use files named 
debian/package.copyright.
.P
Any filenames specified as parameters will be installed into the first
package dh_installdocs is told to act on. By default, this is the first 
binary package in debian/control, but if you use -p, -i, or -a flags, it 
will be the first package specified by those flags.
.P
Also,  debian/README.Debian (or debian/README.debian) and debian/TODO, if 
they exist, will be installed into the first binary package listed in 
debian/control, if dh_installdocs is acting on that package. Note that 
debian/TODO will be installed named TODO.Debian, if the package is not a 
debian native package.
.P
A file named debian/package.docs (debian/docs may be used for the first
binary package in debian/control) can list other files to be installed.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Install files for all architecture dependent packages.
.TP
.B \-i, \--indep
Install files for all architecture independent packages.
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B \-ppackage, \--package=package
Install files for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-A, \--all
Install all files specified by command line parameters in ALL packages
acted on.
.TP
.B file ...
Install these files as documentation into the first package acted on. (Or in
all packages if -A is specified).
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.P
Note that dh_installdocs will happily copy entire directory hierarchies if
you ask it to (it uses cp -a internally). If it is asked to install a
directory, it will install the complete contents of the directory.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH BUGS
Filenames with spaces in them will not currently be installed.
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
