.TH DH_INSTALLMANPAGES 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_installmanpages \- install man pages into package build directories
.SH SYNOPSIS
.B dh_installmanpages
.I "[debhelper options] [file ...]"
.SH "DESCRIPTION"
dh_installmanpages is a debhelper program that is responsible for
automatically installing man pages into usr/man/ and usr/X11R6/man/ in
package build directories.
.P
dh_installmanpages scans the current directory and all subdirectories for
filenames that look like man pages. (Note that only real files are looked
at; symlinks are ignored.) It uses
.BR file (1)
to verify that the files are in the correct format. Then, based on the
files' extensions, it installs them into the correct man directory.
.P
All filenames specified as parameters will be skipped by dh_installmanpages.
This is useful if by default it installs some man pages that you do not want
to be installed.
.P
After the man page installation step, dh_installmanpages will check to see if
any of the man pages are ".so" links. If so, it changes them to symlinks.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B file ...
Do not install these files as man pages, even if they look like valid man
pages.
.SH NOTES
dh_installmanpages will install the man pages it finds into
.B all
packages you tell it to act on, since it can't tell what package the man
pages belong in.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH BUGS
Man pages with the extension
.B .man
are not automatically installed. 
.P
Files specified as parameters that contain spaces in their filenames will
not be processed properly.
.P
By default, all man pages are installed into all binary packages, which is
almost never what you really want (use -p to work around this).
.P
This is a "Do what I Mean" type program - you have been warned!
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
