#!/bin/sh -e
#
# Install cron scripts into the appropriate places.

PATH=debian:$PATH:/usr/lib/debhelper
. dh_lib

for PACKAGE in $DH_DOPACKAGES; do
	TMP=`tmpdir $PACKAGE`

	for type in daily weekly monthly; do
		cron=`pkgfile $PACKAGE cron.$type`
		if [ "$cron" ]; then
			if [ ! -d $TMP/etc/cron.$type ]; then
				doit "install -o root -g root -d $TMP/etc/cron.$type"
			fi
			doit "install "$cron" $TMP/etc/cron.$type/$PACKAGE"
		fi
	done
done
