#!/bin/sh -e
#
# Reads debian/examples, installs all files listed there into
# /usr/doc/$PACKAGE/examples

PATH=debian:$PATH:/usr/lib/debhelper
. dh_lib

for PACKAGE in $DH_DOPACKAGES; do
	TMP=`tmpdir $PACKAGE`
	EXT=`pkgext $PACKAGE`

	examples=""

	if [ -e debian/${EXT}examples ]; then
		examples=`tr "\n" " " < debian/${EXT}examples`
	fi

	if [ "$PACKAGE" = "$MAINPACKAGE" -a "$*" ]; then
		examples="$* $examples"
	fi

	if [ "$examples" ]; then
		if [ ! -d $TMP/usr/doc/$PACKAGE/examples ]; then
			doit "install -d $TMP/usr/doc/$PACKAGE/examples"
		fi

		doit "cp -a $examples $TMP/usr/doc/$PACKAGE/examples/"
	fi
done
