#!/usr/bin/perl

=head1 NAME

dh_listpackages - list binary packages debhelper will act on

=cut

use strict;
use warnings;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_listpackages> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_listpackages> is a debhelper program that outputs a list of all binary
packages debhelper commands will act on. If you pass it some options, it
will change the list to match the packages other debhelper commands would
act on if passed the same options.

=cut

$dh{BLOCK_NOOP_WARNINGS}=1;
init();
inhibit_log();
print join("\n",@{$dh{DOPACKAGES}})."\n";

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut

# Local Variables:
# indent-tabs-mode: t
# tab-width: 4
# cperl-indent-level: 4
# End:
