.TH DH_LISTPACKAGES 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_listpackages \- list binary packages debhelper will act on
.SH SYNOPSIS
.B dh_listpackages
.I "[debhelper options]"
.SH "DESCRIPTION"
dh_listpackages is a debhelper program that outputs a list of all binary
packages debhelper commands will act on. If you pass it some options, it
will change the list to match the packages other debhelper commands would
act on if passed the same options.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
