.TH DH_LINK 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_link \- create symlinks in package build directories
.SH SYNOPSIS
.B dh_link
.I "[debhelper options] [-A] [source destination ...]"
.SH "DESCRIPTION"
dh_link is a debhelper program that creates symlinks in package build
directories.
.P
dh_link accepts a list of pairs of source and destination files. The source
files are the already existing files that will be symlinked from. The
destination files are the symlinks that will be created. There
.B must
be an equal number of source and destination files specified.
.P
The list can be specified in two ways. A file named debian/package.links
can list pairs of files. If you use this file, you should put each pair
of files on its own line, and separate the files within the pair with
whitespace. Also, pairs of files can be specified as parameters - these
pairs will only be created in the package build directory of the first
package dh_link is told to act on. By default, this is the first binary
package in debian/control, but if you use -p, -i, or -a flags, it will be
the first package specified by those flags.
.P
Be sure you
.B do
specify the full filename to both the source and destination files (unlike
you would do if you were using something like
.BR ln (1)
).
.P
dh_link will generate symlinks that comply with debian policy - absolute
when policy says they should be absolute, and relative links with as short a
path as possible. It will also create any subdirectories it needs to to put
the symlinks in.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-A, \--all
Create any links specified by command line parameters in ALL packages
acted on, not just the first.
.TP
.B source destination ...
Create a file named "destination" as a link to a file named "source". Do
this in the package build directory of the first package acted on.
(Or in all packages if -A is specified.)
.SH EXAMPLES
 dh_link usr/share/man/man1/foo.1 usr/share/man/man1/bar.1
.P
Make bar.1 be a symlink to foo.1
.P
 dh_link var/lib/foo usr/lib/foo \\
  usr/X11R6/man/man1/foo.1x usr/share/man/man1/bar.1
.P
Make /usr/lib/foo/ be a link to /var/lib/foo/, and bar.1 be a symlink to the
X man page foo.1x
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH BUGS
It's impossible to specify filenames with spaces or other whitespace in them
in debian/package.links files. This is more a historical design flaw than a
bug.
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@debian.org>
