#!/usr/bin/perl -w
#
# Generate a DEBIAN/md5sums file, that lists the md5sums of all files in the
# package.

use Cwd;
BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);

	if (! -d "$TMP/DEBIAN") {
		doit("install","-d","$TMP/DEBIAN");
	}

	# Check if we should exclude conffiles.
	my $exclude="";
	if (! $dh{INCLUDE} && -r "$TMP/DEBIAN/conffiles") {
		# Generate exclude regexp.
		open (CONFF,"$TMP/DEBIAN/conffiles");
		while (<CONFF>) {
			chomp;
			s/^\///;
			$exclude.="! -path \"$_\" ";
		}
		close CONFF;
	}

	$olddir=getcwd();
	complex_doit("cd $TMP ; find * -type f $exclude ! -regex '^DEBIAN/.*' -print0 | xargs -r0 md5sum > DEBIAN/md5sums ; cd $olddir");
	# If the file's empty, no reason to waste inodes on it.
	if (-z "$TMP/DEBIAN/md5sums") {
		doit("rm","-f","$TMP/DEBIAN/md5sums");
	}
	else {
		doit("chmod",644,"$TMP/DEBIAN/md5sums");
		doit("chown","root.root","$TMP/DEBIAN/md5sums");
	}
}
