.TH DH_MD5SUMS 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_md5sums \- generate DEBIAN/md5sums file (deprecated)
.SH SYNOPSIS
.B dh_md5sums
.I "[debhelper options] [-x]"
.SH "DESCRIPTION"
dh_md5sums is a debhelper program that is responsible for generating
a DEBIAN/md5sums file, which lists the md5sums of each file in the package.
.P
All files in DEBIAN/ are omitted from the md5sums file, as are all conffiles
(unless you use the -x switch).
.P
The md5sums file is installed with proper permissions and ownerships.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-x, \--include-conffiles
Include conffiles in the md5sums list. Note that this is redundant, and
included elsewhere in debian packages.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
