#!/bin/sh -e
#
# Automatically generate shlibs files.

PATH=debian:$PATH:/usr/lib/debhelper
. dh_lib

for PACKAGE in $DH_DOPACKAGES; do
	TMP=`tmpdir $PACKAGE`

	if [ -e "$TMP/DEBIAN/shlibs" ]; then
		error "$TMP/DEBIAN/shlibs already exists."
	fi

	for file in `find $TMP -type f -name "*.so*" | tr "\n" " "` ; do
		LIBRARY=`expr $file : ".*/\(.*\)\.so\..*"` || true
		VERSION=`expr $file : ".*/.*\.so\.\(.*\)"` || true
		MAJOR=`expr $VERSION : "\([0-9]*\)\."` || true
		LIBSTUB=`expr $file : "\(.*\/.*\.so\)\..*"` || true
		if [ ! -d "$TMP/DEBIAN" ] ; then
			doit "install -d $TMP/DEBIAN"
		fi
		doit "echo '$LIBRARY $MAJOR $PACKAGE" >>$TMP/DEBIAN/shlibs"
	done

	if [ -e "$TMP/DEBIAN/shlibs" ]; then
		doit "chown root.root $TMP/DEBIAN/shlibs"
	fi
done
