#!/usr/bin/perl -w
#
# Automatically generate shlibs files.

BEGIN { push @INC, "debian", "/usr/share/debhelper" }
use Dh_Lib;
init();

foreach $PACKAGE (@{$dh{DOPACKAGES}}) {
	$TMP=tmpdir($PACKAGE);

	doit("rm", "-f", "$TMP/DEBIAN/shlibs");

	open (FIND, "find $TMP -type f -name '*.so.*' |");
	while (<FIND>) {
		chomp;
		($library, $major)=m#.*/(.*)\.so\.(\d*)\.?#;
		if (defined($dh{M_PARAMS}) && $dh{M_PARAMS} ne '') {
			$major=$dh{M_PARAMS};
		}
		if (! -d "$TMP/DEBIAN") {
			doit("install","-d","$TMP/DEBIAN");
		}
		$deps=$PACKAGE;
		if ($dh{V_FLAG_SET}) {
			if ($dh{V_FLAG} ne '') {
				$deps=$dh{V_FLAG};
			}	
			else {
				# Call isnative becuase it sets $dh{VERSION}
				# as a side effect.
				isnative($PACKAGE);
				$deps="$PACKAGE (>= $dh{VERSION})";
			}
		}
		if (defined($library) && defined($major) && defined($deps) && 
		    $library ne '' && $major ne '' && $deps ne '') {
			complex_doit("echo '$library $major $deps' >>$TMP/DEBIAN/shlibs");
		}
	}
	close FIND;

	if (-e "$TMP/DEBIAN/shlibs") {
		doit("chmod",644,"$TMP/DEBIAN/shlibs");
		doit("chown","root.root","$TMP/DEBIAN/shlibs");
	}
}
