.TH DH_MOVEFILES 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_movefiles \- move files out of debian/tmp into subpackages
.SH SYNOPSIS
.B dh_movefiles
.I "[debhelper options] [--sourcedir=dir] [file ..]"
.SH "DESCRIPTION"
dh_movefiles is a debhelper program that is responsible for moving files out
of debian/tmp or some other directory and into other package build
directories. This may be useful if your package has a Makefile that installs
everything into debian/tmp, and you need to break that up into subpackages.
.P
Files named debian/package.files list the files to be moved, separated by
whitespace. The filenames listed should be relative to debian/tmp/. You can
also list directory names, and the whole directory will be moved. You can
even use wildcards if you like. If you prefer, you can list the files to
move on the command line and this will apply to the first package
dh_movefiles is told to act on.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B --sourcedir=dir
Instead of moving files out of debian/tmp (the default), this option makes
it move files out of some other directory. Since the entire contents of
the sourcedir is moved, specifiying something like --sourcedir=/ is very
unsafe, so to prevent mistakes, the sourcedir must be a relative filename; it
cannot begin with a `/'.
.TP
.B file ..
Lists files to move. The filenames listed should be relative to debian/tmp/.
You can also list directory names, and the whole directory will be moved. You
can even use wildcards if you like. It is an error to list files here unless
you use -p, -i, or -a to tell dh_movefiles which subpackage to put them in.
.SH NOTES
Note that files are always moved out of debian/tmp by default (even if you
have instructed debhelper to use a compatability level higher than one,
which does not otherwise use debian/tmp for anything at all). The idea
behind this is that the package that is being built can be told to install
into debian/tmp, and then files can be moved by dh_movefiles from that
directory. Any files or directories that remain are ignored, and get
deleted by dh_clean later.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@debian.org>
