.TH DH_SUIDREGISTER 1
.SH NAME
dh_suidregister \- set up package to register files with suidregister
.SH SYNOPSIS
.B dh_suidregister
.I "[-v] [-a] [-i] [--no-act] [-ppackage] [-Ptmpdir] [-A] [file ...]"
.SH "DESCRIPTION"
dh_suidregister is a debhelper program that is responsible for modifying the
postinst and postrm scripts of a package so the package will register files
with 
.BR suidregister (1)
when it is installed.
.P
Any filenames specified as parameters will be registered in the first 
package dh_suidregister is told to act on. By default, this is the first 
binary package in debian/control, but if you use -p, -i, or -a flags, 
it will be the first package specified by those flags.
.P
Files named debian/package.suid (or debian/suid for the first binary package
in debian/control) can list other files to be registered.
.P
If neither of these methods is used to specify files, dh_suidregister will
scan the package build directory for files that have suid permissions, and
will automatically register all files it finds.
.P
Note that this package modifies your postinst and postrm files. See
.BR dh_installdeb (1)
for an explanation of how this works.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Register files for all architecture dependent packages.
.TP
.B \-i, \--indep
Register files for all architecture independent packages.
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B \-ppackage, \--package=package
Register files for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-A, \--all
Register any files specified by command line parameters in ALL packages
acted on. I doubt anyone will find this useful, it's here for consitency
with other debhelper programs.
.TP
.B file ...
Register these files in the first package acted on. (Or in all packages if
-A is specified.)
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
,
.BR suidregister (8)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
