.TH DH_SUIDREGISTER 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_suidregister \- obsolete suid registration program
.SH SYNOPSIS
Do not run
.SH "DESCRIPTION"
This program used to register suid and sgid files with 
.BR suidregister (1)
, but with the introduction of
.BR dpkg-statoverride (8)
, registration of files in this way is unnecessary, and even harmful, so 
this program no longer does anything, and you can remove it from any rules
file that uses it.
.P
If your package registered things with suidregister before, you need to
make sure that you add a versioned conflict, as follows:
  Conflicts: suidmanager (<< 0.50)
.P
This is not done automatically. If your program did not previously use
suidregister, you do not have to add the conflict.
.SH "SEE ALSO"
.TP
.BR debhelper (1)
.TP
.BR suidregister (8)
.TP
.BR dpkg-statoverride (8)
.SH AUTHOR
Joey Hess <joeyh@debian.org>
