#!/usr/bin/perl -w

=head1 NAME

dh_scrollkeeper - deprecated no-op

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_scrollkeeper> [S<I<debhelper options>>] [B<-n>] [S<I<directory>>]

=head1 DESCRIPTION

B<dh_scrollkeeper> was a debhelper program that handled 
registering OMF files for ScrollKeeper. However, it no longer does
anything, and is now deprecated.

=cut

init();

warning("This program is deprecated, and does nothing anymore.");

=head1 SEE ALSO

L<debhelper>

This program is a part of debhelper.

=head1 AUTHOR

Ross Burton <ross@burtonini.com>

=cut
