.TH DH_INSTALLDEBFILES 1
.SH NAME
dh_shlibdeps \- calculate shared library dependancies
.SH SYNOPSIS
.B dh_shlibdeps
.I "[-v] [-a] [-i] [-ppackage] [-Ptmpdir] [-uparams]"
.SH "DESCRIPTION"
dh_shlibdeps is a debhelper program that is responsible for calculating
shared library dependancies for all executables found in the package build
directory.
.P
This program is merely a wrapper around
.BR dpkg-shlibdeps (1)
that calls it once for each package listed in the control file. You may 
prefer to simply run 
.BR dpkg-shlibdeps (1)
by hand.
.SH OPTIONS
.TP
.B \-v
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a
Install files for all architecture dependent packages.
.TP
.B \-i
Install files for all architecture independent packages.
.TP
.B \-ppackage
Install files for the package named "package".
.TP
.B \-Ptmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-uparams
Pass "params" to 
.BR dpkg-shlibdeps (1)
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.BR dpkg-shlibdeps (1)
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
