.TH DH_SHLIBDEPS 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_shlibdeps \- calculate shared library dependancies
.SH SYNOPSIS
.B dh_shlibdeps
.I "[debhelper options] [-ldirectory] [-uparams] [-Xitem] [-- params]"
.SH "DESCRIPTION"
dh_shlibdeps is a debhelper program that is responsible for calculating
shared library dependancies for packages.
.P
This program is merely a wrapper around
.BR dpkg-shlibdeps (1)
that calls it once for each package listed in the control file, passing it
a list of ELF executables and shared libraries it has found.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-uparams, \--dpkg-shlibdeps-params=params
.TP
.B \-\- params
Pass "params" to 
.BR dpkg-shlibdeps (1)
.TP
.B \-Xitem, \--exclude=item 
Exclude files that contain "item" anywhere in their filename from being
passed to dpkg-shlibdeps. This will make their dependancies be ignored.
This may be useful in some situations, but use it with caution.
.TP
.B \-ldirectory
Before
.BR dpkg-shlibdeps (1)
is run, LD_LIBRARY_PATH will be set to the specified directory.
This is useful for multi-binary packages where a library
is built in one package and another package contains binaries linked
against said library.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.TP
.BR debhelper (1)
.TP
.BR dpkg-shlibdeps (1)
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@debian.org>
