.TH DH_STRIP 1
.SH NAME
dh_strip \- strip executables, shared libraries, and some static libraries.
.SH SYNOPSIS
.B dh_strip
.I "[-v] [-a] [-i] [--no-act] [-Ptmpdir] [-ppackage]"
.SH "DESCRIPTION"
dh_strip is a debhelper program that is responsible for stripping
executables, shared libraries, and static libraries that are not used for
debugging.
.P
It assumes that files that have names like lib*_g.a are static libraries
used in debugging, and will not strip them.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Strip files in all architecture dependent packages.
.TP
.B \-i, \--indep
Strip files in all architecture independent packages (likely, this is
pointless :-).
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B \-ppackage, \--package=package
Strip files for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will have their files stripped.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
