.TH DH_STRIP 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_strip \- strip executables, shared libraries, and some static libraries.
.SH SYNOPSIS
.B dh_strip
.I "[debhelper options] [-Xitem]"
.SH "DESCRIPTION"
dh_strip is a debhelper program that is responsible for stripping
executables, shared libraries, and static libraries that are not used for
debugging.
.P
It assumes that files that have names like lib*_g.a are static libraries
used in debugging, and will not strip them.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-Xitem, \--exclude=item
Exclude files that contain "item" anywhere in their filename from being
stripped. You may use this option multiple times to build up a list of
things to exclude.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
