#!/usr/bin/perl -w
#
# Obsolete.

use strict;
use Debian::Debhelper::Dh_Lib;
init();

my $notused=1;

foreach my $package (@{$dh{DOPACKAGES}}) {
	my $tmp=tmpdir($package);
	my $suid=pkgfile($package,"suid");

	# All this code is here just to see if we would have done something
	# before..

	my @files;
	if ($suid) {
		@files=filearray($suid, $tmp);
	}

	if (($package eq $dh{FIRSTPACKAGE} || $dh{PARAMS_ALL}) && @ARGV) {
		push @files, @ARGV;
	}

	if (! @files && ! $suid) {
		# No files specified (and no empty debian/suid file), so
		# guess what files to process.
		@files=split(/\n/,`find $tmp -type f -perm +6000`);
	}

	if (@files) {
		# So we would have registered some files before.
		error("This program should no longer be used, but you need to add a conflicts with \"suidmanager (<< 0.50)\". Please read the dh_suidregister(1) man page.");
	}
}

# Although they called it, it's not going to do anything.
if ($notused) {
	warning("This program is obsolete and may be safely removed from your rules file.");
}
