.TH DH_TESTROOT 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_testroot \- ensure that a package is built as root
.SH SYNOPSIS
.B dh_testroot
.I "[debhelper options]"
.SH "DESCRIPTION"
dh_testroot simply checks to see if you are root. If not, it exits with an
error. Debian packages must be built as root, though you can use
.BR fakeroot (1)
to work around this.
.SH OPTIONS
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.BR debhelper (1)
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
