#!/usr/bin/perl -w
#
# Checks to make sure we are building the package in the right directory.
# Tests for the existance of debian/control, and for the existance
# of any other files you specify on the command line.

use strict;
use Debian::Debhelper::Dh_Lib;
init();

foreach my $file ('debian/control', @ARGV) {
	if (! -e $file) {
		error("\"$file\" not found. Are you sure you are in the correct directory?");
	}
}
