#!/usr/bin/perl

=head1 NAME

dh_testroot - ensure that a package is built as root

=head1 SYNOPSIS

B<dh_testroot> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_testroot> simply checks to see if you are root. If not, it exits with an
error. Debian packages must be built as root, though you can use 
L<fakeroot(1)>

=cut

use strict;
use warnings;
use Debian::Debhelper::Dh_Lib;
inhibit_log();

if ($< != 0) {
	error("You must run this as root (or use fakeroot).");
}

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut

# Local Variables:
# indent-tabs-mode: t
# tab-width: 4
# cperl-indent-level: 4
# End:
