#!/usr/bin/perl -w
#
# Debhelper version check.

BEGIN { push @INC, "debian", "/usr/lib/debhelper" }
use Dh_Lib;
use Dh_Version; # contains the version number of debhelper.
init();

my($compare, $ver);

if ($#ARGV > 0) {
	$compare=shift;
	$ver=shift;
}
elsif ($#ARGV eq 0) {
	$compare=">=";
	$ver=shift;
}

if (defined $compare and defined $ver) {
	system('dpkg','--compare-versions',$Dh_Version::version,$compare,$ver) == 0 ||
		error("debhelper version $Dh_Version::version is installed, but a version $compare $ver is needed to build this package.");
}
