#!/usr/bin/perl -w

=head1 NAME

dh_testroot - ensure that a package is built as root

=head1 SYNOPSIS

B<dh_testroot> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_testroot simply checks to see if you are root. If not, it exits with an
error. Debian packages must be built as root, though you can use 
L<fakeroot(1)>

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

if ($< != 0) {
	error("You must run this as root (or use fakeroot).");
}

=head1 SEE ALSO

L<debhelper(1)>

This program is a part of debhelper.

=head1 AUTHOR

Joey Hess <joeyh@debian.org>

=cut
