.TH DH_TESTDIR 1
.SH NAME
dh_testdir \- test directory before building debian package
.SH SYNOPSIS
.B dh_testdir
.I "[-v] [file ...]"
.SH "DESCRIPTION"
dh_testdir tries to make sure that you are in the correct directory when
building a debian package. It makes sure that the file debian/control
exists, as well as any other files you specify. If not,
it exits with an error.
.SH OPTIONS
.TP
.B \-v
Verbose mode; show all commands that modify the package build directory.
This currently has no effect.
.TP
.B file ...
Test for the existence of these files.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
.SH BUGS
Files with spaces in their names will not be processed correctly.
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
