.TH DH_UNDOCUMENTED 1 "" "Debhelper Commands" "Debhelper Commands"
.SH NAME
dh_undocumented \- make symlinks to undocumented.7.gz man page
.SH SYNOPSIS
.B dh_undocumented
.I "[debhelper options [-A] [manpage ...]"
.SH "DESCRIPTION"
dh_undocumented is a debhelper program that is responsible for making
symlinks to the
.BR undocumented (7)
man page for man pages that are not present in your package.
.P
The program takes a list of man pages that should be symlinked to
.BR undocumented (7)
It determines what directory the man pages should be placed in by examining
their extensions - pages ending in "x" go into /usr/X11R6/man/, while pages
that end in anything else go in /usr/share/man/. It also examines the extension
to see what section the man page belongs in. After figuring this out, it
generates the necessary symlinks to
.BR undocumented (7)
, placing the sylinks in the package build directory.
.P
The lists of man pages that need
.BR undocumented (7)
symlinks can be specified in two ways. Any man page names specified as
parameters will be set up in the first package dh_undocumented is told
to act on. By default, this is the first binary package in debian/control,
but if you use -p, -i, or -a flags, it will be the first package specified
by those flags.
Also, a file named debian/package.undocumented can list other man page names
to set up.
.SH OPTIONS
.TP
.TP
.B debhelper options
See
.BR debhelper (1)
for a list of options common to all debhelper commands.
.TP
.B \-A, \--all
Install undocumented man page symlinks for any man pages specified by
command line parameters in ALL packages acted on. I doubt anyone will find
this useful, it's here for consitency with other debhelper programs.
.TP
.B manpage ...
Install undocumented man page symlinks for each of these man pages
into the first package acted on. (Or in all packages acted on if -A is
specified.)
.SH ENVIRONMENT
See
.BR debhelper (1)
for a list of environment variables that affect all debhelper commands.
.SH "SEE ALSO"
.TP
.BR debhelper (1)
.TP
.BR undocumented (7)
.SH "CONFORMS TO"
Debian policy, version 3.0.1
.SH AUTHOR
Joey Hess <joeyh@debian.org>
