.TH DH_UNDOCUMENTED 1
.SH NAME
dh_undocumented \- make symlinks to undocumented.7.gz man page
.SH SYNOPSIS
.B dh_undocumented
.I "[-v] [-a] [-i] [--no-act] [-ppackage] [-Ptmpdir] [-A] [manpage ...]"
.SH "DESCRIPTION"
dh_undocumented is a debhelper program that is responsible for making
symlinks to the
.BR undocumented (7)
man page for man pages that are not present in your package.
.P
The program takes a list of man pages that should be symlinked to
.BR undocumented (7)
It determines what directory the man pages should be placed in by examining
their extensions - pages ending in "x" go into /usr/X11R6/man/, while pages
that end in anything else go in /usr/man/. It also examines the extention to
see what section the man page belongs in. After figuring this out, it
generates the necessary symlinks to
.BR undocumented (7)
, placing the sylinks in the package build directory.
.P
The lists of man pages that need 
.BR undocumented (7)
symlinks can be specified in two ways. Any man page names specified as
parameters will be set up in the first package dh_undocumented is told
to act on. By default, this is the first binary package in debian/control, 
but if you use -p, -i, or -a flags, it will be the first package specified 
by those flags.
Also, a file named debian/package.undocumented (or debian/undocumented, for 
the first binary package in debian/control) can list other man page names to
set up.
.SH OPTIONS
.TP
.B \-v, \--verbose
Verbose mode; show all commands that modify the package build directory.
.TP
.B \-a, \--arch
Install undocumented man page symlinks for all architecture dependent packages.
.TP
.B \-i, \--indep
Install undocumented man page symlinks for all architecture independent packages.
.TP
.B \--no-act
Do not really do anything. If used with -v, the result is that this command
will output a list of what it would have done.
.TP
.B \-ppackage, \--package=package
Install undocumented man page symlinks for the package named "package".
.TP
.B \-Ptmpdir, \--tmpdir=tmpdir
Use "tmpdir" for package build directory. 
.TP
.B \-A, \--all
Install undocumented man page symlinks for any man pages specified by 
command line parameters in ALL packages acted on. I doubt anyone will find
this useful, it's here for consitency with other debhelper programs.
.TP
.B manpage ...
Install undocumented man page symlinks for each of these man pages
into the first package acted on. (Or in all packages acted on if -A is
specified.)
.SH NOTES
The
.B \-a
.B \-i
and
.B \-p
arguments are cumulative. If none are specified, then all packages listed in
the control file will be effected.
.SH ENVIRONMENT
.TP
.I DH_VERBOSE
Enables verbose mode
.TP
.I DH_NO_ACT
Enables no-act mode (see above).
.SH "SEE ALSO"
.BR /usr/doc/debhelper/README
,
.BR undocumented (7)
.SH "CONFORMS TO"
Debian policy, version 2.3.0.0
.SH AUTHOR
Joey Hess <joeyh@master.debian.org>
