#!/bin/sh
# Run a debhelper command using files from this directory.

# Run items from current directory by preference.
PATH=.:$PATH
export PATH

# Ensure that builds are self-hosting, which means I have to use the .pm
# files in this package, not any that may be on the system.
export PERL5LIB=$(pwd)

# If any automatic script generation is done in building this package, 
# be sure to use the new templates from this package.
export DH_AUTOSCRIPTDIR=$(pwd)/autoscripts

prog=$1
shift 1

exec $prog "$@"
