#!/bin/sh -e
# Clean up after cvs's dreadful symlink handling, by making all the symlinks
# this package needs.
ln -sf postinst-menu autoscripts/postrm-menu
ln -sf postinst-modules autoscripts/postrm-modules
ln -sf postinst-mime autoscripts/postrm-mime
