#!/usr/bin/perl
use Test;
plan(tests => 3);

# It used to not make absolute links in this situation, and it should.
# #37774
system("./dh_link","etc/foo","usr/lib/bar");
ok("/etc/foo",readlink("debian/debhelper/usr/lib/bar"));

# let's make sure it makes simple relative links ok.
system("./dh_link","usr/bin/foo","usr/bin/bar");
ok("foo",readlink("debian/debhelper/usr/bin/bar"));

# ok, more complex relative links.
system("./dh_link","usr/lib/1","usr/bin/2");
ok("../lib/1",readlink("debian/debhelper/usr/bin/2"));
